/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CBS;

import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Geethan
 */
public class EBE_Home extends javax.swing.JFrame {

    /**
     * Creates new form EBE_Home
     */
    public EBE_Home() {
        initComponents();
        showUserTable();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        pnl_side = new javax.swing.JPanel();
        sidepnl_top = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btn_Dashboard = new javax.swing.JPanel();
        leftpnl_dashboard_btn = new javax.swing.JPanel();
        lbl_dashboard_btn = new javax.swing.JLabel();
        btn_addroutes = new javax.swing.JPanel();
        leftpnl_addroutes_btn = new javax.swing.JPanel();
        lbl_manageroutes_btn1 = new javax.swing.JLabel();
        btn_allroutes = new javax.swing.JPanel();
        leftpnl_allroutes_btn = new javax.swing.JPanel();
        lbl_manageroutes_btn2 = new javax.swing.JLabel();
        btn_editroutes = new javax.swing.JPanel();
        leftpnl_manageroutes_btn = new javax.swing.JPanel();
        lbl_manageroutes_btn = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JPanel();
        leftpnl_logout_btn = new javax.swing.JPanel();
        lbl_settings_btn = new javax.swing.JLabel();
        pnl_center = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_dashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        pnl_addroutes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_routeid = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        checkbox_mon = new javax.swing.JCheckBox();
        checkbox_tue = new javax.swing.JCheckBox();
        checkbox_wed = new javax.swing.JCheckBox();
        checkbox_thu = new javax.swing.JCheckBox();
        checkbox_fri = new javax.swing.JCheckBox();
        checkbox_sat = new javax.swing.JCheckBox();
        checkbox_sun = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        spinner_capacity = new javax.swing.JSpinner();
        btn_addroutesaddform = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btn_addroutescancelform = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        textfield_deptime = new javax.swing.JTextField();
        textfield_journeyprice = new javax.swing.JTextField();
        txtfield_deptCountry = new javax.swing.JTextField();
        txtfield_deptTown = new javax.swing.JTextField();
        txtfield_destCountry = new javax.swing.JTextField();
        txtfield_destTown = new javax.swing.JTextField();
        pnl_allroutes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_allroutes = new javax.swing.JTable();
        pnl_editroutes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btn_addroutescancelform1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btn_addroutesaddform1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        spinner_capacity1 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        textfield_journeyprice1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        textfield_deptime1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbl_routeid1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pnl_settings = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1540, 815));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setPreferredSize(new java.awt.Dimension(1366, 768));

        bg.setLayout(new java.awt.BorderLayout());

        pnl_side.setBackground(new java.awt.Color(21, 25, 28));
        pnl_side.setPreferredSize(new java.awt.Dimension(320, 720));
        pnl_side.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepnl_top.setBackground(new java.awt.Color(21, 25, 28));
        sidepnl_top.setPreferredSize(new java.awt.Dimension(480, 165));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("Europe Bus Employees");

        javax.swing.GroupLayout sidepnl_topLayout = new javax.swing.GroupLayout(sidepnl_top);
        sidepnl_top.setLayout(sidepnl_topLayout);
        sidepnl_topLayout.setHorizontalGroup(
            sidepnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepnl_topLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel23)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        sidepnl_topLayout.setVerticalGroup(
            sidepnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepnl_topLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel23)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pnl_side.add(sidepnl_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 320, -1));

        btn_Dashboard.setBackground(new java.awt.Color(34, 40, 44));
        btn_Dashboard.setPreferredSize(new java.awt.Dimension(480, 55));
        btn_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_DashboardMousePressed(evt);
            }
        });

        leftpnl_dashboard_btn.setBackground(new java.awt.Color(0, 102, 255));
        leftpnl_dashboard_btn.setPreferredSize(new java.awt.Dimension(5, 55));

        javax.swing.GroupLayout leftpnl_dashboard_btnLayout = new javax.swing.GroupLayout(leftpnl_dashboard_btn);
        leftpnl_dashboard_btn.setLayout(leftpnl_dashboard_btnLayout);
        leftpnl_dashboard_btnLayout.setHorizontalGroup(
            leftpnl_dashboard_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        leftpnl_dashboard_btnLayout.setVerticalGroup(
            leftpnl_dashboard_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbl_dashboard_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_dashboard_btn.setForeground(new java.awt.Color(204, 204, 204));
        lbl_dashboard_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_dashboard_btn.setText("Dashboard");
        lbl_dashboard_btn.setPreferredSize(new java.awt.Dimension(116, 55));

        javax.swing.GroupLayout btn_DashboardLayout = new javax.swing.GroupLayout(btn_Dashboard);
        btn_Dashboard.setLayout(btn_DashboardLayout);
        btn_DashboardLayout.setHorizontalGroup(
            btn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_DashboardLayout.createSequentialGroup()
                .addComponent(leftpnl_dashboard_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(lbl_dashboard_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        btn_DashboardLayout.setVerticalGroup(
            btn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftpnl_dashboard_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_dashboard_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_side.add(btn_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 320, -1));

        btn_addroutes.setBackground(new java.awt.Color(21, 25, 28));
        btn_addroutes.setPreferredSize(new java.awt.Dimension(480, 55));
        btn_addroutes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addroutesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addroutesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addroutesMousePressed(evt);
            }
        });

        leftpnl_addroutes_btn.setBackground(new java.awt.Color(21, 25, 28));
        leftpnl_addroutes_btn.setPreferredSize(new java.awt.Dimension(5, 55));

        javax.swing.GroupLayout leftpnl_addroutes_btnLayout = new javax.swing.GroupLayout(leftpnl_addroutes_btn);
        leftpnl_addroutes_btn.setLayout(leftpnl_addroutes_btnLayout);
        leftpnl_addroutes_btnLayout.setHorizontalGroup(
            leftpnl_addroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        leftpnl_addroutes_btnLayout.setVerticalGroup(
            leftpnl_addroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        lbl_manageroutes_btn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_manageroutes_btn1.setForeground(new java.awt.Color(204, 204, 204));
        lbl_manageroutes_btn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_manageroutes_btn1.setText("ADD Routes");

        javax.swing.GroupLayout btn_addroutesLayout = new javax.swing.GroupLayout(btn_addroutes);
        btn_addroutes.setLayout(btn_addroutesLayout);
        btn_addroutesLayout.setHorizontalGroup(
            btn_addroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addroutesLayout.createSequentialGroup()
                .addComponent(leftpnl_addroutes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(lbl_manageroutes_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        btn_addroutesLayout.setVerticalGroup(
            btn_addroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftpnl_addroutes_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_manageroutes_btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_side.add(btn_addroutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 320, -1));

        btn_allroutes.setBackground(new java.awt.Color(21, 25, 28));
        btn_allroutes.setPreferredSize(new java.awt.Dimension(480, 55));
        btn_allroutes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_allroutesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_allroutesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_allroutesMousePressed(evt);
            }
        });

        leftpnl_allroutes_btn.setBackground(new java.awt.Color(21, 25, 28));
        leftpnl_allroutes_btn.setPreferredSize(new java.awt.Dimension(5, 55));

        javax.swing.GroupLayout leftpnl_allroutes_btnLayout = new javax.swing.GroupLayout(leftpnl_allroutes_btn);
        leftpnl_allroutes_btn.setLayout(leftpnl_allroutes_btnLayout);
        leftpnl_allroutes_btnLayout.setHorizontalGroup(
            leftpnl_allroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        leftpnl_allroutes_btnLayout.setVerticalGroup(
            leftpnl_allroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        lbl_manageroutes_btn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_manageroutes_btn2.setForeground(new java.awt.Color(204, 204, 204));
        lbl_manageroutes_btn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_manageroutes_btn2.setText("All Routes");

        javax.swing.GroupLayout btn_allroutesLayout = new javax.swing.GroupLayout(btn_allroutes);
        btn_allroutes.setLayout(btn_allroutesLayout);
        btn_allroutesLayout.setHorizontalGroup(
            btn_allroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_allroutesLayout.createSequentialGroup()
                .addComponent(leftpnl_allroutes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(lbl_manageroutes_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        btn_allroutesLayout.setVerticalGroup(
            btn_allroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftpnl_allroutes_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_manageroutes_btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_side.add(btn_allroutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 320, -1));

        btn_editroutes.setBackground(new java.awt.Color(21, 25, 28));
        btn_editroutes.setPreferredSize(new java.awt.Dimension(480, 55));
        btn_editroutes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editroutesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editroutesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editroutesMousePressed(evt);
            }
        });

        leftpnl_manageroutes_btn.setBackground(new java.awt.Color(21, 25, 28));
        leftpnl_manageroutes_btn.setPreferredSize(new java.awt.Dimension(5, 55));

        javax.swing.GroupLayout leftpnl_manageroutes_btnLayout = new javax.swing.GroupLayout(leftpnl_manageroutes_btn);
        leftpnl_manageroutes_btn.setLayout(leftpnl_manageroutes_btnLayout);
        leftpnl_manageroutes_btnLayout.setHorizontalGroup(
            leftpnl_manageroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        leftpnl_manageroutes_btnLayout.setVerticalGroup(
            leftpnl_manageroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        lbl_manageroutes_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_manageroutes_btn.setForeground(new java.awt.Color(204, 204, 204));
        lbl_manageroutes_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_manageroutes_btn.setText("Edit Routes");

        javax.swing.GroupLayout btn_editroutesLayout = new javax.swing.GroupLayout(btn_editroutes);
        btn_editroutes.setLayout(btn_editroutesLayout);
        btn_editroutesLayout.setHorizontalGroup(
            btn_editroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_editroutesLayout.createSequentialGroup()
                .addComponent(leftpnl_manageroutes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(lbl_manageroutes_btn)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        btn_editroutesLayout.setVerticalGroup(
            btn_editroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftpnl_manageroutes_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_manageroutes_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_side.add(btn_editroutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 320, -1));

        btn_Logout.setBackground(new java.awt.Color(21, 25, 28));
        btn_Logout.setPreferredSize(new java.awt.Dimension(480, 55));
        btn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_LogoutMousePressed(evt);
            }
        });

        leftpnl_logout_btn.setBackground(new java.awt.Color(21, 25, 28));
        leftpnl_logout_btn.setPreferredSize(new java.awt.Dimension(5, 55));

        javax.swing.GroupLayout leftpnl_logout_btnLayout = new javax.swing.GroupLayout(leftpnl_logout_btn);
        leftpnl_logout_btn.setLayout(leftpnl_logout_btnLayout);
        leftpnl_logout_btnLayout.setHorizontalGroup(
            leftpnl_logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        leftpnl_logout_btnLayout.setVerticalGroup(
            leftpnl_logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbl_settings_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_settings_btn.setForeground(new java.awt.Color(204, 204, 204));
        lbl_settings_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_settings_btn.setText("Log out");

        javax.swing.GroupLayout btn_LogoutLayout = new javax.swing.GroupLayout(btn_Logout);
        btn_Logout.setLayout(btn_LogoutLayout);
        btn_LogoutLayout.setHorizontalGroup(
            btn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_LogoutLayout.createSequentialGroup()
                .addComponent(leftpnl_logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(lbl_settings_btn)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        btn_LogoutLayout.setVerticalGroup(
            btn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftpnl_logout_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_settings_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        pnl_side.add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 320, -1));

        bg.add(pnl_side, java.awt.BorderLayout.WEST);

        pnl_center.setBackground(new java.awt.Color(34, 40, 44));
        pnl_center.setPreferredSize(new java.awt.Dimension(1440, 815));
        pnl_center.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(34, 40, 44));

        pnl_dashboard.setBackground(new java.awt.Color(34, 40, 44));
        pnl_dashboard.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Dashboard");

        jPanel5.setPreferredSize(new java.awt.Dimension(925, 5));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_dashboardLayout = new javax.swing.GroupLayout(pnl_dashboard);
        pnl_dashboard.setLayout(pnl_dashboardLayout);
        pnl_dashboardLayout.setHorizontalGroup(
            pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dashboardLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnl_dashboardLayout.setVerticalGroup(
            pnl_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_dashboardLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(784, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", pnl_dashboard);

        pnl_addroutes.setBackground(new java.awt.Color(34, 40, 44));
        pnl_addroutes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("ADD routes");
        pnl_addroutes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 27, -1, -1));

        jPanel6.setPreferredSize(new java.awt.Dimension(925, 5));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        pnl_addroutes.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 78, -1, -1));

        lbl_routeid.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_routeid.setForeground(new java.awt.Color(204, 204, 204));
        lbl_routeid.setText("Route ID : 0000");
        pnl_addroutes.add(lbl_routeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Select Depature :");
        pnl_addroutes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Capacity                 :");
        pnl_addroutes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Town :");
        pnl_addroutes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Select Destination");
        pnl_addroutes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Country :");
        pnl_addroutes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Town :");
        pnl_addroutes.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Country :");
        pnl_addroutes.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        checkbox_mon.setForeground(new java.awt.Color(204, 204, 204));
        checkbox_mon.setText("MON");
        pnl_addroutes.add(checkbox_mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        checkbox_tue.setForeground(new java.awt.Color(204, 204, 204));
        checkbox_tue.setText("TUE");
        pnl_addroutes.add(checkbox_tue, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        checkbox_wed.setForeground(new java.awt.Color(204, 204, 204));
        checkbox_wed.setText("WED");
        pnl_addroutes.add(checkbox_wed, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        checkbox_thu.setForeground(new java.awt.Color(204, 204, 204));
        checkbox_thu.setText("THU");
        pnl_addroutes.add(checkbox_thu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        checkbox_fri.setForeground(new java.awt.Color(204, 204, 204));
        checkbox_fri.setText("FRI");
        pnl_addroutes.add(checkbox_fri, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, -1, -1));

        checkbox_sat.setForeground(new java.awt.Color(204, 204, 204));
        checkbox_sat.setText("SAT");
        pnl_addroutes.add(checkbox_sat, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, -1, -1));

        checkbox_sun.setForeground(new java.awt.Color(204, 204, 204));
        checkbox_sun.setText("SUN");
        pnl_addroutes.add(checkbox_sun, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Select Available days of the Week");
        pnl_addroutes.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Set Depature time :");
        pnl_addroutes.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Journey Price         :");
        pnl_addroutes.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));
        pnl_addroutes.add(spinner_capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 630, 190, -1));

        btn_addroutesaddform.setBackground(new java.awt.Color(0, 102, 255));
        btn_addroutesaddform.setForeground(new java.awt.Color(204, 204, 204));
        btn_addroutesaddform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addroutesaddformMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addroutesaddformMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addroutesaddformMousePressed(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ADD");

        javax.swing.GroupLayout btn_addroutesaddformLayout = new javax.swing.GroupLayout(btn_addroutesaddform);
        btn_addroutesaddform.setLayout(btn_addroutesaddformLayout);
        btn_addroutesaddformLayout.setHorizontalGroup(
            btn_addroutesaddformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addroutesaddformLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        btn_addroutesaddformLayout.setVerticalGroup(
            btn_addroutesaddformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addroutesaddformLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_addroutes.add(btn_addroutesaddform, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 710, 110, 30));

        btn_addroutescancelform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addroutescancelformMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addroutescancelformMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cancel");

        javax.swing.GroupLayout btn_addroutescancelformLayout = new javax.swing.GroupLayout(btn_addroutescancelform);
        btn_addroutescancelform.setLayout(btn_addroutescancelformLayout);
        btn_addroutescancelformLayout.setHorizontalGroup(
            btn_addroutescancelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addroutescancelformLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        btn_addroutescancelformLayout.setVerticalGroup(
            btn_addroutescancelformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addroutescancelformLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_addroutes.add(btn_addroutescancelform, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 710, 110, 30));
        pnl_addroutes.add(textfield_deptime, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 190, -1));
        pnl_addroutes.add(textfield_journeyprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 190, -1));
        pnl_addroutes.add(txtfield_deptCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 100, -1));
        pnl_addroutes.add(txtfield_deptTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 120, -1));
        pnl_addroutes.add(txtfield_destCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 100, -1));
        pnl_addroutes.add(txtfield_destTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 130, -1));

        jTabbedPane1.addTab("tab2", pnl_addroutes);

        pnl_allroutes.setBackground(new java.awt.Color(34, 40, 44));
        pnl_allroutes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setText("All Routes");
        pnl_allroutes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 27, 239, -1));

        jPanel9.setPreferredSize(new java.awt.Dimension(925, 5));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        pnl_allroutes.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 78, -1, -1));

        table_allroutes.setBackground(new java.awt.Color(34, 40, 44));
        table_allroutes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_allroutes.setForeground(new java.awt.Color(204, 204, 204));
        table_allroutes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RouteID", "DeptCT", "DestCT", "DeptTime", "Price", "Capacity"
            }
        ));
        table_allroutes.setFocusable(false);
        table_allroutes.setRowHeight(35);
        table_allroutes.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table_allroutes.setSelectionForeground(new java.awt.Color(34, 40, 44));
        table_allroutes.setShowVerticalLines(true);
        table_allroutes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_allroutes);

        pnl_allroutes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 920, 680));

        jTabbedPane1.addTab("tab4", pnl_allroutes);

        pnl_editroutes.setBackground(new java.awt.Color(34, 40, 44));
        pnl_editroutes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setText("Edit Routes");
        pnl_editroutes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 27, 239, -1));

        jPanel11.setPreferredSize(new java.awt.Dimension(925, 5));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        pnl_editroutes.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 78, -1, -1));

        btn_addroutescancelform1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addroutescancelform1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addroutescancelform1MouseExited(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Delete");

        javax.swing.GroupLayout btn_addroutescancelform1Layout = new javax.swing.GroupLayout(btn_addroutescancelform1);
        btn_addroutescancelform1.setLayout(btn_addroutescancelform1Layout);
        btn_addroutescancelform1Layout.setHorizontalGroup(
            btn_addroutescancelform1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addroutescancelform1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        btn_addroutescancelform1Layout.setVerticalGroup(
            btn_addroutescancelform1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addroutescancelform1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_editroutes.add(btn_addroutescancelform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 110, 30));

        btn_addroutesaddform1.setBackground(new java.awt.Color(0, 102, 255));
        btn_addroutesaddform1.setForeground(new java.awt.Color(204, 204, 204));
        btn_addroutesaddform1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addroutesaddform1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addroutesaddform1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addroutesaddform1MousePressed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Update");

        javax.swing.GroupLayout btn_addroutesaddform1Layout = new javax.swing.GroupLayout(btn_addroutesaddform1);
        btn_addroutesaddform1.setLayout(btn_addroutesaddform1Layout);
        btn_addroutesaddform1Layout.setHorizontalGroup(
            btn_addroutesaddform1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addroutesaddform1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        btn_addroutesaddform1Layout.setVerticalGroup(
            btn_addroutesaddform1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_addroutesaddform1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_editroutes.add(btn_addroutesaddform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 110, 30));
        pnl_editroutes.add(spinner_capacity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 190, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Capacity                 :");
        pnl_editroutes.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));
        pnl_editroutes.add(textfield_journeyprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 190, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Journey Price         :");
        pnl_editroutes.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));
        pnl_editroutes.add(textfield_deptime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 190, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Set Depature time :");
        pnl_editroutes.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Country /Town:");
        pnl_editroutes.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Destination :");
        pnl_editroutes.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Country/Town :");
        pnl_editroutes.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("Depature :");
        pnl_editroutes.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        lbl_routeid1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbl_routeid1.setForeground(new java.awt.Color(204, 204, 204));
        lbl_routeid1.setText("Route ID : ");
        pnl_editroutes.add(lbl_routeid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));
        pnl_editroutes.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 90, -1));
        pnl_editroutes.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 90, -1));
        pnl_editroutes.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 90, -1));

        jButton1.setText("Find by ID ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnl_editroutes.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 110, -1));

        jTabbedPane1.addTab("tab4", pnl_editroutes);

        pnl_settings.setBackground(new java.awt.Color(34, 40, 44));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Settings");

        jPanel8.setPreferredSize(new java.awt.Dimension(925, 5));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_settingsLayout = new javax.swing.GroupLayout(pnl_settings);
        pnl_settings.setLayout(pnl_settingsLayout);
        pnl_settingsLayout.setHorizontalGroup(
            pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_settingsLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_settingsLayout.setVerticalGroup(
            pnl_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_settingsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(784, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", pnl_settings);

        pnl_center.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1060, 900));

        bg.add(pnl_center, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    GUI_Methods gui = new GUI_Methods();
    private boolean dashboard=true,adr=false,ar=false,er=false,set=false;
    private void btn_DashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMousePressed
        // TODO add your handling code here:
        gui.setcolor_sidebar_button(btn_Dashboard,leftpnl_dashboard_btn);
        gui.resetcolor_sidebar_button(btn_addroutes,leftpnl_addroutes_btn);
        gui.resetcolor_sidebar_button(btn_allroutes,leftpnl_allroutes_btn);
        gui.resetcolor_sidebar_button(btn_editroutes,leftpnl_manageroutes_btn);
        gui.resetcolor_sidebar_button(btn_Logout,leftpnl_logout_btn);
        dashboard = true;
        adr = false;
        ar = false;
        er=false;
        set = false;
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btn_DashboardMousePressed

    private void btn_LogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMousePressed
        // TODO add your handling code here:
        gui.setcolor_sidebar_button(btn_Logout,leftpnl_logout_btn);
        gui.resetcolor_sidebar_button(btn_Dashboard,leftpnl_dashboard_btn);
        gui.resetcolor_sidebar_button(btn_editroutes,leftpnl_manageroutes_btn);
        gui.resetcolor_sidebar_button(btn_addroutes,leftpnl_addroutes_btn);
        gui.resetcolor_sidebar_button(btn_allroutes,leftpnl_allroutes_btn);
        
        set = true;
        adr=false;
        ar = false;
        dashboard = false;
        er = false;
        jTabbedPane1.setSelectedIndex(4);
        logout();
    }//GEN-LAST:event_btn_LogoutMousePressed

    private void btn_DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseEntered
        // TODO add your handling code here:
        
        gui.hoverset_sidebar_button(btn_Dashboard);
         
       
        
    }//GEN-LAST:event_btn_DashboardMouseEntered

    private void btn_DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseExited
        // TODO add your handling code here:
        if(dashboard==false){
        gui.hoverreset_sidebar_button(btn_Dashboard);
        }
    }//GEN-LAST:event_btn_DashboardMouseExited

    private void btn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseEntered
        // TODO add your handling code here:
        gui.hoverset_sidebar_button(btn_Logout);
    }//GEN-LAST:event_btn_LogoutMouseEntered

    private void btn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LogoutMouseExited
        // TODO add your handling code here:
        if(set==false){
        gui.hoverreset_sidebar_button(btn_Logout);
        }
    }//GEN-LAST:event_btn_LogoutMouseExited

    private void btn_editroutesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editroutesMouseEntered
        // TODO add your handling code here:
        gui.hoverset_sidebar_button(btn_editroutes);
    }//GEN-LAST:event_btn_editroutesMouseEntered

    private void btn_editroutesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editroutesMouseExited
        // TODO add your handling code here:
        if(er==false){
            gui.hoverreset_sidebar_button(btn_editroutes);
        }
    }//GEN-LAST:event_btn_editroutesMouseExited

    private void btn_editroutesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editroutesMousePressed
        // TODO add your handling code here:
        gui.setcolor_sidebar_button(btn_editroutes,leftpnl_manageroutes_btn);
        gui.resetcolor_sidebar_button(btn_Dashboard,leftpnl_dashboard_btn);
        gui.resetcolor_sidebar_button(btn_Logout,leftpnl_logout_btn);
        gui.resetcolor_sidebar_button(btn_addroutes,leftpnl_addroutes_btn);
        gui.resetcolor_sidebar_button(btn_allroutes,leftpnl_allroutes_btn);
        er = true;
        dashboard = false;
        adr=false;
        ar = false;
        set = false;
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btn_editroutesMousePressed

    private void btn_addroutesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutesMouseEntered
        // TODO add your handling code here:
        gui.hoverset_sidebar_button(btn_addroutes);
    }//GEN-LAST:event_btn_addroutesMouseEntered

    private void btn_addroutesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutesMouseExited
        // TODO add your handling code here:
        if(adr==false){
            gui.hoverreset_sidebar_button(btn_addroutes);
        }
    }//GEN-LAST:event_btn_addroutesMouseExited

    private void btn_addroutesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutesMousePressed
        // TODO add your handling code here:
        gui.setcolor_sidebar_button(btn_addroutes,leftpnl_addroutes_btn);
        gui.resetcolor_sidebar_button(btn_Dashboard,leftpnl_dashboard_btn);
        gui.resetcolor_sidebar_button(btn_Logout,leftpnl_logout_btn);
        gui.resetcolor_sidebar_button(btn_editroutes,leftpnl_manageroutes_btn);
        gui.resetcolor_sidebar_button(btn_allroutes,leftpnl_allroutes_btn);
        adr = true;
        dashboard = false;
        ar=false;
        er = false;
        set = false;
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btn_addroutesMousePressed

    private void btn_allroutesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_allroutesMouseEntered
        // TODO add your handling code here:
        gui.hoverset_sidebar_button(btn_allroutes);
    }//GEN-LAST:event_btn_allroutesMouseEntered

    private void btn_allroutesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_allroutesMouseExited
        // TODO add your handling code here:
        if(ar==false){
            gui.hoverreset_sidebar_button(btn_allroutes);
        }
    }//GEN-LAST:event_btn_allroutesMouseExited

    private void btn_allroutesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_allroutesMousePressed
        // TODO add your handling code here:
        gui.setcolor_sidebar_button(btn_allroutes,leftpnl_allroutes_btn);
        gui.resetcolor_sidebar_button(btn_Dashboard,leftpnl_dashboard_btn);
        gui.resetcolor_sidebar_button(btn_Logout,leftpnl_logout_btn);
        gui.resetcolor_sidebar_button(btn_editroutes,leftpnl_manageroutes_btn);
        gui.resetcolor_sidebar_button(btn_addroutes,leftpnl_addroutes_btn);
        ar = true;
        dashboard = false;
        adr=false;
        er = false;
        set = false;
        jTabbedPane1.setSelectedIndex(2);
        
    }//GEN-LAST:event_btn_allroutesMousePressed

    private void btn_addroutesaddformMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutesaddformMouseEntered
        // TODO add your handling code here:
        gui.hoverset_pnlcenter_button(btn_addroutesaddform);
    }//GEN-LAST:event_btn_addroutesaddformMouseEntered

    private void btn_addroutesaddformMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutesaddformMouseExited
        // TODO add your handling code here:
        gui.hoverreset_pnlcenter_addbutton(btn_addroutesaddform);
    }//GEN-LAST:event_btn_addroutesaddformMouseExited

    private void btn_addroutescancelformMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutescancelformMouseEntered
        // TODO add your handling code here:
        gui.hoverset_pnlcenter_button(btn_addroutescancelform);
    }//GEN-LAST:event_btn_addroutescancelformMouseEntered

    private void btn_addroutescancelformMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutescancelformMouseExited
        // TODO add your handling code here:
        gui.hoverreset_pnlcenter_cancelbutton(btn_addroutescancelform);
    }//GEN-LAST:event_btn_addroutescancelformMouseExited

    private void btn_addroutescancelform1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutescancelform1MouseEntered
        // TODO add your handling code here:
        gui.hoverset_pnlcenter_button(btn_addroutescancelform1);
    }//GEN-LAST:event_btn_addroutescancelform1MouseEntered

    private void btn_addroutescancelform1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutescancelform1MouseExited
        // TODO add your handling code here:
        gui.hoverreset_pnlcenter_cancelbutton(btn_addroutescancelform1);
    }//GEN-LAST:event_btn_addroutescancelform1MouseExited

    private void btn_addroutesaddform1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutesaddform1MouseEntered
        // TODO add your handling code here:
        gui.hoverset_pnlcenter_button(btn_addroutesaddform1);
    }//GEN-LAST:event_btn_addroutesaddform1MouseEntered

    private void btn_addroutesaddform1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutesaddform1MouseExited
        // TODO add your handling code here:
        gui.hoverreset_pnlcenter_addbutton(btn_addroutesaddform1);
    }//GEN-LAST:event_btn_addroutesaddform1MouseExited

    private void btn_addroutesaddformMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutesaddformMousePressed
        // TODO add your handling code here:
     boolean selected1 = checkbox_mon.isSelected();
     boolean selected2 = checkbox_tue.isSelected();
     boolean selected3 = checkbox_wed.isSelected();
     boolean selected4 = checkbox_thu.isSelected();
     boolean selected5 = checkbox_fri.isSelected();
     boolean selected6 = checkbox_sat.isSelected();
     boolean selected7 = checkbox_sun.isSelected();
     
     String deptCountry = txtfield_deptCountry.getText();
     String deptCity = txtfield_deptTown.getText();
     String destCountry = txtfield_destCountry.getText();
     String destCity = txtfield_destTown.getText();
     String deptTime = textfield_deptime.getText();
     float price =Float.parseFloat(textfield_journeyprice.getText());
     
     String deptCT=deptCountry+" "+ deptCity;
     String destCT=destCountry+" "+ destCity;
     
     int capacity =(Integer) spinner_capacity.getValue();
     
     ClassAdmin obj=new ClassAdmin(deptCT,destCT,deptTime,price,capacity);
     obj.addRoute();
     obj.checkBoxHandle(selected1,selected2,selected3,selected4,selected5,selected6,selected7);
     
    }//GEN-LAST:event_btn_addroutesaddformMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String getID =jTextField2.getText();
        String setDeptCT;
           try{
        String selectQuery="select * from routetable WHERE routeid= '"+getID+"' ";
        DB_Connection selectobj=new DB_Connection();
        ResultSet rs=selectobj.Select(selectQuery);
        while(rs.next())
            {
                getID=Integer.toString(rs.getInt("routeid"));
                
                jTextField3.setText(rs.getString("deptCT"));
                jTextField1.setText(rs.getString("destCT"));
                textfield_deptime1.setText(rs.getString("deptTime"));
                textfield_journeyprice1.setText(rs.getString("price"));
                spinner_capacity1.setValue(rs.getString("capacity"));
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_addroutesaddform1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addroutesaddform1MousePressed
         // TODO add your handling code here:
     String getID =jTextField2.getText();  
     String deptCT = jTextField3.getText();
     String destCT = jTextField1.getText();
     String destTime = textfield_deptime1.getText();
     String price = textfield_journeyprice1.getText();
     int   capacity =(Integer) spinner_capacity1.getValue();
     //float price =Float.parseFloat(textfield_journeyprice.getText());
     String sql = "UPDATE routetable SET deptCT= '"+deptCT+"', destCT= '"+destCT+"' , deptTime = '"+destTime+"', price= '"+price+"',capacity= '"+capacity+"' WHERE  routeID='" + getID + "'";
      DB_Connection selectobj=new DB_Connection();
      selectobj.update(sql);
    }//GEN-LAST:event_btn_addroutesaddform1MousePressed

    public ArrayList<ModelRoute> routeList(){
         ArrayList<ModelRoute> routeList =new ArrayList<>();
        try{
            String selectQuery="select * from routetable";
            DB_Connection selectobj=new DB_Connection();
            ResultSet rs=selectobj.Select(selectQuery);
            ModelRoute modelRoute;
        while(rs.next())
            {
                modelRoute=new ModelRoute(rs.getInt("routeID"),rs.getString("deptCT"),rs.getString("destCT"),rs.getString("deptTime"),rs.getString("price"),rs.getInt("capacity"));
                routeList.add(modelRoute);
            }
        
   
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        return routeList;
    }
    
        public void showUserTable(){
           ArrayList<ModelRoute> List =routeList();
           DefaultTableModel model;
           model = (DefaultTableModel)table_allroutes.getModel();
           Object[] row=new Object[6];
           for(int i=0;i<List.size();i++){
            row[0]=List.get(i).routeID();
            row[1]=List.get(i).getDeptCT();
            row[2]=List.get(i).getDestCT();
            row[3]=List.get(i).getDeptTime();
            row[4]=List.get(i).getPrice();
            row[5]=List.get(i).getCapacity();
            model.addRow(row);
           }
    
    }
    
     public void logout(){
        String id="1";
        String loginid;
        String lo="0";
        try{
        String selectQuery="select * from logs WHERE islogin='"+id+"' ";
       
        DB_Connection selectobj=new DB_Connection();
        ResultSet rs=selectobj.Select(selectQuery);
        while(rs.next())
            {
                //selectedId=Integer.toString(rs.getInt("routeid"));
                loginid=rs.getString("logid");
                System.out.println(loginid);
                String update="UPDATE logs SET islogin= '"+lo+"'  WHERE  logid = '" + loginid + "' ";
                selectobj.update(update);
                Login logo = new Login();
                logo.setVisible(true);
                this.setVisible(false);
                
            }   
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
      
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EBE_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EBE_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EBE_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EBE_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EBE_Home().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_Dashboard;
    private javax.swing.JPanel btn_Logout;
    private javax.swing.JPanel btn_addroutes;
    private javax.swing.JPanel btn_addroutesaddform;
    private javax.swing.JPanel btn_addroutesaddform1;
    private javax.swing.JPanel btn_addroutescancelform;
    private javax.swing.JPanel btn_addroutescancelform1;
    private javax.swing.JPanel btn_allroutes;
    private javax.swing.JPanel btn_editroutes;
    private javax.swing.JCheckBox checkbox_fri;
    private javax.swing.JCheckBox checkbox_mon;
    private javax.swing.JCheckBox checkbox_sat;
    private javax.swing.JCheckBox checkbox_sun;
    private javax.swing.JCheckBox checkbox_thu;
    private javax.swing.JCheckBox checkbox_tue;
    private javax.swing.JCheckBox checkbox_wed;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl_dashboard_btn;
    private javax.swing.JLabel lbl_manageroutes_btn;
    private javax.swing.JLabel lbl_manageroutes_btn1;
    private javax.swing.JLabel lbl_manageroutes_btn2;
    private javax.swing.JLabel lbl_routeid;
    private javax.swing.JLabel lbl_routeid1;
    private javax.swing.JLabel lbl_settings_btn;
    private javax.swing.JPanel leftpnl_addroutes_btn;
    private javax.swing.JPanel leftpnl_allroutes_btn;
    private javax.swing.JPanel leftpnl_dashboard_btn;
    private javax.swing.JPanel leftpnl_logout_btn;
    private javax.swing.JPanel leftpnl_manageroutes_btn;
    private javax.swing.JPanel pnl_addroutes;
    private javax.swing.JPanel pnl_allroutes;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_dashboard;
    private javax.swing.JPanel pnl_editroutes;
    private javax.swing.JPanel pnl_settings;
    private javax.swing.JPanel pnl_side;
    private javax.swing.JPanel sidepnl_top;
    private javax.swing.JSpinner spinner_capacity;
    private javax.swing.JSpinner spinner_capacity1;
    private javax.swing.JTable table_allroutes;
    private javax.swing.JTextField textfield_deptime;
    private javax.swing.JTextField textfield_deptime1;
    private javax.swing.JTextField textfield_journeyprice;
    private javax.swing.JTextField textfield_journeyprice1;
    private javax.swing.JTextField txtfield_deptCountry;
    private javax.swing.JTextField txtfield_deptTown;
    private javax.swing.JTextField txtfield_destCountry;
    private javax.swing.JTextField txtfield_destTown;
    // End of variables declaration//GEN-END:variables
}
