/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CBS;



/**
 *
 * @author Geethan
 */
public class EBE_Home extends javax.swing.JFrame {

    /**
     * Creates new form EBE_Home
     */
    public EBE_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        pnl_side = new javax.swing.JPanel();
        sidepnl_top = new javax.swing.JPanel();
        btn_Dashboard = new javax.swing.JPanel();
        leftpnl_dashboard_btn = new javax.swing.JPanel();
        lbl_dashboard_btn = new javax.swing.JLabel();
        btn_Manageroutes = new javax.swing.JPanel();
        leftpnl_manageroutes_btn = new javax.swing.JPanel();
        lbl_manageroutes_btn = new javax.swing.JLabel();
        btn_Allroutes = new javax.swing.JPanel();
        leftpnl_allroutes_btn = new javax.swing.JPanel();
        lbl_allroutes_btn = new javax.swing.JLabel();
        btn_Settings = new javax.swing.JPanel();
        leftpnl_settings_btn = new javax.swing.JPanel();
        lbl_settings_btn = new javax.swing.JLabel();
        pnl_center = new javax.swing.JPanel();

        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 720));

        bg.setLayout(new java.awt.BorderLayout());

        pnl_side.setBackground(new java.awt.Color(21, 25, 28));
        pnl_side.setPreferredSize(new java.awt.Dimension(480, 720));
        pnl_side.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepnl_top.setBackground(new java.awt.Color(21, 25, 28));
        sidepnl_top.setPreferredSize(new java.awt.Dimension(480, 165));

        javax.swing.GroupLayout sidepnl_topLayout = new javax.swing.GroupLayout(sidepnl_top);
        sidepnl_top.setLayout(sidepnl_topLayout);
        sidepnl_topLayout.setHorizontalGroup(
            sidepnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        sidepnl_topLayout.setVerticalGroup(
            sidepnl_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        pnl_side.add(sidepnl_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        btn_Dashboard.setBackground(new java.awt.Color(34, 40, 44));
        btn_Dashboard.setPreferredSize(new java.awt.Dimension(480, 55));
        btn_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_DashboardMousePressed(evt);
            }
        });

        leftpnl_dashboard_btn.setBackground(new java.awt.Color(0, 102, 255));
        leftpnl_dashboard_btn.setPreferredSize(new java.awt.Dimension(5, 55));

        javax.swing.GroupLayout leftpnl_dashboard_btnLayout = new javax.swing.GroupLayout(leftpnl_dashboard_btn);
        leftpnl_dashboard_btn.setLayout(leftpnl_dashboard_btnLayout);
        leftpnl_dashboard_btnLayout.setHorizontalGroup(
            leftpnl_dashboard_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        leftpnl_dashboard_btnLayout.setVerticalGroup(
            leftpnl_dashboard_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbl_dashboard_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_dashboard_btn.setForeground(new java.awt.Color(204, 204, 204));
        lbl_dashboard_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_dashboard_btn.setText("Dashboard");
        lbl_dashboard_btn.setPreferredSize(new java.awt.Dimension(116, 55));

        javax.swing.GroupLayout btn_DashboardLayout = new javax.swing.GroupLayout(btn_Dashboard);
        btn_Dashboard.setLayout(btn_DashboardLayout);
        btn_DashboardLayout.setHorizontalGroup(
            btn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_DashboardLayout.createSequentialGroup()
                .addComponent(leftpnl_dashboard_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(lbl_dashboard_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        btn_DashboardLayout.setVerticalGroup(
            btn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftpnl_dashboard_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_dashboard_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_side.add(btn_Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, -1, -1));

        btn_Manageroutes.setBackground(new java.awt.Color(21, 25, 28));
        btn_Manageroutes.setPreferredSize(new java.awt.Dimension(480, 55));
        btn_Manageroutes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ManageroutesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ManageroutesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ManageroutesMousePressed(evt);
            }
        });

        leftpnl_manageroutes_btn.setBackground(new java.awt.Color(21, 25, 28));
        leftpnl_manageroutes_btn.setPreferredSize(new java.awt.Dimension(5, 55));

        javax.swing.GroupLayout leftpnl_manageroutes_btnLayout = new javax.swing.GroupLayout(leftpnl_manageroutes_btn);
        leftpnl_manageroutes_btn.setLayout(leftpnl_manageroutes_btnLayout);
        leftpnl_manageroutes_btnLayout.setHorizontalGroup(
            leftpnl_manageroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        leftpnl_manageroutes_btnLayout.setVerticalGroup(
            leftpnl_manageroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        lbl_manageroutes_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_manageroutes_btn.setForeground(new java.awt.Color(204, 204, 204));
        lbl_manageroutes_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_manageroutes_btn.setText("Manage routes");

        javax.swing.GroupLayout btn_ManageroutesLayout = new javax.swing.GroupLayout(btn_Manageroutes);
        btn_Manageroutes.setLayout(btn_ManageroutesLayout);
        btn_ManageroutesLayout.setHorizontalGroup(
            btn_ManageroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ManageroutesLayout.createSequentialGroup()
                .addComponent(leftpnl_manageroutes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(lbl_manageroutes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        btn_ManageroutesLayout.setVerticalGroup(
            btn_ManageroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftpnl_manageroutes_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_manageroutes_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_side.add(btn_Manageroutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        btn_Allroutes.setBackground(new java.awt.Color(21, 25, 28));
        btn_Allroutes.setPreferredSize(new java.awt.Dimension(480, 55));
        btn_Allroutes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AllroutesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AllroutesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AllroutesMousePressed(evt);
            }
        });

        leftpnl_allroutes_btn.setBackground(new java.awt.Color(21, 25, 28));
        leftpnl_allroutes_btn.setPreferredSize(new java.awt.Dimension(5, 55));

        javax.swing.GroupLayout leftpnl_allroutes_btnLayout = new javax.swing.GroupLayout(leftpnl_allroutes_btn);
        leftpnl_allroutes_btn.setLayout(leftpnl_allroutes_btnLayout);
        leftpnl_allroutes_btnLayout.setHorizontalGroup(
            leftpnl_allroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        leftpnl_allroutes_btnLayout.setVerticalGroup(
            leftpnl_allroutes_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        lbl_allroutes_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_allroutes_btn.setForeground(new java.awt.Color(204, 204, 204));
        lbl_allroutes_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_allroutes_btn.setText("All Routes");

        javax.swing.GroupLayout btn_AllroutesLayout = new javax.swing.GroupLayout(btn_Allroutes);
        btn_Allroutes.setLayout(btn_AllroutesLayout);
        btn_AllroutesLayout.setHorizontalGroup(
            btn_AllroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_AllroutesLayout.createSequentialGroup()
                .addComponent(leftpnl_allroutes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(lbl_allroutes_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        btn_AllroutesLayout.setVerticalGroup(
            btn_AllroutesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftpnl_allroutes_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_allroutes_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnl_side.add(btn_Allroutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        btn_Settings.setBackground(new java.awt.Color(21, 25, 28));
        btn_Settings.setPreferredSize(new java.awt.Dimension(480, 55));
        btn_Settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SettingsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_SettingsMousePressed(evt);
            }
        });

        leftpnl_settings_btn.setBackground(new java.awt.Color(21, 25, 28));
        leftpnl_settings_btn.setPreferredSize(new java.awt.Dimension(5, 55));

        javax.swing.GroupLayout leftpnl_settings_btnLayout = new javax.swing.GroupLayout(leftpnl_settings_btn);
        leftpnl_settings_btn.setLayout(leftpnl_settings_btnLayout);
        leftpnl_settings_btnLayout.setHorizontalGroup(
            leftpnl_settings_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        leftpnl_settings_btnLayout.setVerticalGroup(
            leftpnl_settings_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbl_settings_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_settings_btn.setForeground(new java.awt.Color(204, 204, 204));
        lbl_settings_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_settings_btn.setText("Settings");

        javax.swing.GroupLayout btn_SettingsLayout = new javax.swing.GroupLayout(btn_Settings);
        btn_Settings.setLayout(btn_SettingsLayout);
        btn_SettingsLayout.setHorizontalGroup(
            btn_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_SettingsLayout.createSequentialGroup()
                .addComponent(leftpnl_settings_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(lbl_settings_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        btn_SettingsLayout.setVerticalGroup(
            btn_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftpnl_settings_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_settings_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        pnl_side.add(btn_Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, -1, -1));

        bg.add(pnl_side, java.awt.BorderLayout.WEST);

        pnl_center.setBackground(new java.awt.Color(34, 40, 44));
        pnl_center.setPreferredSize(new java.awt.Dimension(1440, 660));

        javax.swing.GroupLayout pnl_centerLayout = new javax.swing.GroupLayout(pnl_center);
        pnl_center.setLayout(pnl_centerLayout);
        pnl_centerLayout.setHorizontalGroup(
            pnl_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        pnl_centerLayout.setVerticalGroup(
            pnl_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        bg.add(pnl_center, java.awt.BorderLayout.CENTER);

        getContentPane().add(bg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    GUI_Methods gui = new GUI_Methods();
    private boolean dashboard=true,mr=false,ar=false,set=false;
    private void btn_DashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMousePressed
        // TODO add your handling code here:
        gui.setcolor_sidebar_button(btn_Dashboard,leftpnl_dashboard_btn);
        gui.resetcolor_sidebar_button(btn_Manageroutes,leftpnl_manageroutes_btn);
        gui.resetcolor_sidebar_button(btn_Allroutes,leftpnl_allroutes_btn);
        gui.resetcolor_sidebar_button(btn_Settings,leftpnl_settings_btn);
        dashboard = true;
        mr = false;
        ar = false;
        set = false;
    }//GEN-LAST:event_btn_DashboardMousePressed

    private void btn_ManageroutesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageroutesMousePressed
        // TODO add your handling code here:
        gui.setcolor_sidebar_button(btn_Manageroutes,leftpnl_manageroutes_btn);
        gui.resetcolor_sidebar_button(btn_Dashboard,leftpnl_dashboard_btn);
        gui.resetcolor_sidebar_button(btn_Allroutes,leftpnl_allroutes_btn);
        gui.resetcolor_sidebar_button(btn_Settings,leftpnl_settings_btn);
        mr = true;
        dashboard = false;
        ar = false;
        set = false;
    }//GEN-LAST:event_btn_ManageroutesMousePressed

    private void btn_AllroutesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AllroutesMousePressed
        // TODO add your handling code here:
        gui.setcolor_sidebar_button(btn_Allroutes,leftpnl_allroutes_btn);
        gui.resetcolor_sidebar_button(btn_Dashboard,leftpnl_dashboard_btn);
        gui.resetcolor_sidebar_button(btn_Manageroutes,leftpnl_manageroutes_btn);
        gui.resetcolor_sidebar_button(btn_Settings,leftpnl_settings_btn);
        ar = true;
        dashboard = false;
        mr = false;
        set = false;
    }//GEN-LAST:event_btn_AllroutesMousePressed

    private void btn_SettingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingsMousePressed
        // TODO add your handling code here:
        gui.setcolor_sidebar_button(btn_Settings,leftpnl_settings_btn);
        gui.resetcolor_sidebar_button(btn_Dashboard,leftpnl_dashboard_btn);
        gui.resetcolor_sidebar_button(btn_Manageroutes,leftpnl_manageroutes_btn);
        gui.resetcolor_sidebar_button(btn_Allroutes,leftpnl_allroutes_btn);
        set = true;
        ar = false;
        dashboard = false;
        mr = false;
    }//GEN-LAST:event_btn_SettingsMousePressed

    private void btn_DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseEntered
        // TODO add your handling code here:
        gui.hoverset_sidebar_button(btn_Dashboard);
    }//GEN-LAST:event_btn_DashboardMouseEntered

    private void btn_DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DashboardMouseExited
        // TODO add your handling code here:
        if(dashboard==false){
        gui.hoverreset_sidebar_button(btn_Dashboard);
        }
    }//GEN-LAST:event_btn_DashboardMouseExited

    private void btn_ManageroutesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageroutesMouseEntered
        // TODO add your handling code here:
        gui.hoverset_sidebar_button(btn_Manageroutes);
    }//GEN-LAST:event_btn_ManageroutesMouseEntered

    private void btn_ManageroutesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ManageroutesMouseExited
        // TODO add your handling code here:
        if(mr==false){
        gui.hoverreset_sidebar_button(btn_Manageroutes);
        }
    }//GEN-LAST:event_btn_ManageroutesMouseExited

    private void btn_AllroutesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AllroutesMouseEntered
        // TODO add your handling code here:
        gui.hoverset_sidebar_button(btn_Allroutes);
    }//GEN-LAST:event_btn_AllroutesMouseEntered

    private void btn_AllroutesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AllroutesMouseExited
        // TODO add your handling code here:
        if(ar==false){
        gui.hoverreset_sidebar_button(btn_Allroutes);
        }
    }//GEN-LAST:event_btn_AllroutesMouseExited

    private void btn_SettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingsMouseEntered
        // TODO add your handling code here:
        gui.hoverset_sidebar_button(btn_Settings);
    }//GEN-LAST:event_btn_SettingsMouseEntered

    private void btn_SettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SettingsMouseExited
        // TODO add your handling code here:
        if(set==false){
        gui.hoverreset_sidebar_button(btn_Settings);
        }
    }//GEN-LAST:event_btn_SettingsMouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EBE_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EBE_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EBE_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EBE_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EBE_Home().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_Allroutes;
    private javax.swing.JPanel btn_Dashboard;
    private javax.swing.JPanel btn_Manageroutes;
    private javax.swing.JPanel btn_Settings;
    private javax.swing.JLabel lbl_allroutes_btn;
    private javax.swing.JLabel lbl_dashboard_btn;
    private javax.swing.JLabel lbl_manageroutes_btn;
    private javax.swing.JLabel lbl_settings_btn;
    private javax.swing.JPanel leftpnl_allroutes_btn;
    private javax.swing.JPanel leftpnl_dashboard_btn;
    private javax.swing.JPanel leftpnl_manageroutes_btn;
    private javax.swing.JPanel leftpnl_settings_btn;
    private javax.swing.JPanel pnl_center;
    private javax.swing.JPanel pnl_side;
    private javax.swing.JPanel sidepnl_top;
    // End of variables declaration//GEN-END:variables
}
